---

- name: install OpenHPC repository
  yum:
    name: "https://github.com/openhpc/ohpc/releases/download/v{{ lustre_ohpc_version }}.GA/ohpc-release-{{ lustre_ohpc_version }}-1.el7.x86_64.rpm"
  tags: lustre

- name: install lustre client package
  yum:
    name: "{{ lustre_packages }}"
  tags: lustre

- name: set lnet network in module settings
  lineinfile:
    path: /etc/modprobe.d/lustre.conf
    regexp: '^options lnet networks='
    line: "options lnet networks=\"{{ lustre_lnet }}\""
    create: yes
    mode: 0644
  notify: restart lnet
  tags: lustre

- name: make lnet override directory
  file:
    path: /etc/systemd/system/lnet.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: lustre

- name: copy lnet override
  template:
    src: override.conf
    dest: /etc/systemd/system/lnet.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: restart lnet
  tags: lustre

- name: start and enable LNet service
  systemd:
    name: lnet
    state: started
    enabled: yes
  tags: lustre
